-- =============================================================================
-- TWILIO IVR AUTOMATION & BRUTE-FORCE SYSTEM - FULL SUPABASE DATABASE SCHEMA
-- =============================================================================
-- Compatible with Supabase / PostgreSQL 14+
-- Contains: Tables, Constraints, Indexes, Triggers, RPC Functions, and Realtime Configuration.

-- Enable UUID extension if needed
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- -----------------------------------------------------------------------------
-- 1. PHONE LINES TABLE
-- Tracks active Twilio phone lines available for dialing target IVRs.
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS phone_lines (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    phone_number TEXT NOT NULL UNIQUE,
    status TEXT NOT NULL DEFAULT 'idle' CHECK (status IN ('idle', 'busy', 'offline')),
    current_attempt_id BIGINT NULL,
    attempts_processed INT DEFAULT 0,
    max_attempts INT DEFAULT 999,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- -----------------------------------------------------------------------------
-- 2. ATTEMPTS TABLE
-- Tracks individual IVR call attempts, DTMF transmissions, speech logs, and results.
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS attempts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    batch_id TEXT NOT NULL,
    phone_line_id BIGINT NULL REFERENCES phone_lines(id) ON DELETE SET NULL,
    target_phone_number TEXT NOT NULL DEFAULT '+18009838472',
    test_value TEXT NOT NULL, -- Format: "16DIGITCARD:3DIGITCODE" (e.g. 4520340092380262:001)
    target_test_code TEXT NULL, -- Target code expected by mock/test IVR
    status TEXT NOT NULL DEFAULT 'queued' CHECK (status IN ('queued', 'active', 'completed', 'failed', 'retry')),
    call_sid TEXT NULL,
    duration INT DEFAULT 0,
    retry_count INT DEFAULT 0,
    logs JSONB DEFAULT '[]'::jsonb,
    result_details JSONB DEFAULT '{}'::jsonb,
    recording_url TEXT NULL,
    error TEXT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Foreign key link back from phone_lines to current active attempt
ALTER TABLE phone_lines 
    ADD CONSTRAINT fk_phone_lines_current_attempt 
    FOREIGN KEY (current_attempt_id) 
    REFERENCES attempts(id) 
    ON DELETE SET NULL 
    DEFERRABLE INITIALLY DEFERRED;

-- -----------------------------------------------------------------------------
-- 3. MOCK IVR CONFIGURATIONS TABLE
-- Stores target 16-digit card number and permanently assigned test code configurations.
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS mock_ivr_configs (
    id INT PRIMARY KEY DEFAULT 1,
    sixteenDigit TEXT NULL,
    testCode TEXT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- -----------------------------------------------------------------------------
-- 4. PERFORMANCE INDEXES
-- Optimizes queue processing, status lookups, and webhook routing.
-- -----------------------------------------------------------------------------
CREATE INDEX IF NOT EXISTS idx_attempts_status ON attempts(status);
CREATE INDEX IF NOT EXISTS idx_attempts_test_value ON attempts(test_value);
CREATE INDEX IF NOT EXISTS idx_attempts_call_sid ON attempts(call_sid);
CREATE INDEX IF NOT EXISTS idx_attempts_batch_id ON attempts(batch_id);
CREATE INDEX IF NOT EXISTS idx_attempts_created_at ON attempts(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_phone_lines_status ON phone_lines(status);

-- -----------------------------------------------------------------------------
-- 5. AUTOMATIC TIMESTAMP UPDATE TRIGGER
-- Auto-updates updated_at on row changes.
-- -----------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS update_phone_lines_updated_at ON phone_lines;
CREATE TRIGGER update_phone_lines_updated_at
    BEFORE UPDATE ON phone_lines
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();

DROP TRIGGER IF EXISTS update_attempts_updated_at ON attempts;
CREATE TRIGGER update_attempts_updated_at
    BEFORE UPDATE ON attempts
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();

-- -----------------------------------------------------------------------------
-- 6. ATOMIC CLAIM RPC FUNCTION (claim_next_attempt)
-- Concurrency safe queue claiming using PostgreSQL "FOR UPDATE SKIP LOCKED".
-- -----------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION claim_next_attempt(p_line_id BIGINT)
RETURNS SETOF attempts AS $$
DECLARE
    v_attempt_id BIGINT;
BEGIN
    -- Atomically lock the oldest queued or retry attempt
    SELECT id INTO v_attempt_id
    FROM attempts
    WHERE status IN ('queued', 'retry')
    ORDER BY id ASC
    LIMIT 1
    FOR UPDATE SKIP LOCKED;

    -- If a queued attempt was found, claim it for this phone line
    IF v_attempt_id IS NOT NULL THEN
        UPDATE attempts
        SET status = 'active',
            phone_line_id = p_line_id,
            updated_at = NOW(),
            logs = logs || jsonb_build_array(format('[%s] Call assigned to line ID %s.', NOW()::text, p_line_id))
        WHERE id = v_attempt_id;

        UPDATE phone_lines
        SET status = 'busy',
            current_attempt_id = v_attempt_id,
            updated_at = NOW()
        WHERE id = p_line_id;

        RETURN QUERY SELECT * FROM attempts WHERE id = v_attempt_id;
    END IF;

    RETURN;
END;
$$ LANGUAGE plpgsql;

-- -----------------------------------------------------------------------------
-- 7. SUPABASE REALTIME PUBLICATION SETUP
-- Enables live WebSocket broadcasts for attempt updates and phone line changes.
-- -----------------------------------------------------------------------------
DO $$
BEGIN
    IF EXISTS (SELECT 1 FROM pg_publication WHERE pubname = 'supabase_realtime') THEN
        ALTER PUBLICATION supabase_realtime ADD TABLE attempts;
        ALTER PUBLICATION supabase_realtime ADD TABLE phone_lines;
    END IF;
EXCEPTION WHEN OTHERS THEN
    -- Ignore if tables are already in publication
    NULL;
END $$;
